#+title: Game

kick: bar with 3 levels. when player kicks bar goes down a level and they can't kick when it's empty. it slowly recharges. if the player
succesfully lands a kick the bar goes back up to max.

hold: the player can hold certain enemies and projectiles.

blowy-uppy enemy: multilegged machine-organic hybrid. it walks towards the player and explodes. once the explode sequence has started
it cannot be stopped.
the player can:
- shoot it from afar
- run past it so that it explodes, damaging any enemies nearby.
- kick it into enemies: kicking it primes the explosive.
- more combos involving holding it.

fodder enemy: maybe literally called fodder.

player name: alex, bc it is gender-neutral.

explosive projectile: the player can shoot an explosive projectile. the player can shoot it and hold it and then do various combos.
explosives do knockback to enemies (depending on the enemy) and the player, allowing the player to do combos with it to boost their
speed.

movement: auto-bhopping: holding down space bar will make you bhop.
          quake-strafing: bc it's epic. not sure how much air control to give the player bc some levels may require the player not
          to touch the ground for a while.
          way to change direction quickly without losing speed: would be good so that the player can go FAST and NOT STOP.

note: if the projectile-boost (f + m1) in ultrakill was just one button it wouldn't be as fun.
      if the rocket-jump in tf2 and warfork was just one button it wouldn't be fun (see overwatch 2).
